# Use the official NGINX base image
FROM nginx:latest
#FROM amd64/nginx

WORKDIR /app

# Copy the custom NGINX configuration into the container
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the built Angular app into the appropriate directory in the container
COPY dist /app/angular
#COPY abc /app/angular/public

#RUN chmod -R 755 /usr/share/nginx/html && chown -R nginx:nginx /usr/share/nginx/html

# Expose the port that NGINX will listen on (standard HTTP port)
EXPOSE 80

# The default command to run NGINX
CMD ["nginx", "-g", "daemon off;"]
