# Use official Apache image from Docker Hub
FROM httpd:latest

# Copy the Angular build files from dist/ to the Apache server directory
COPY dist /usr/local/apache2/htdocs/

# Expose port 80 to allow external access
EXPOSE 80
