# Use the official OpenJDK 17 base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the compiled JAR files to the container
COPY core-admin/target/core-admin-0.0.1.jar /app/core-admin-0.0.1.jar


# Expose ports
EXPOSE 8081


# Command to run the start script
CMD ["java", "-jar", "/app/core-admin-0.0.1.jar"]
